BEGIN TRANSACTION;
DROP TABLE IF EXISTS `Tags`;
CREATE TABLE IF NOT EXISTS `Tags` (
	`Id`	INTEGER,
	`Name`	TEXT NOT NULL UNIQUE,
	PRIMARY KEY(`Id`)
);
DROP TABLE IF EXISTS `MediaInfoTags`;
CREATE TABLE IF NOT EXISTS `MediaInfoTags` (
	`Id`	INTEGER,
	`MediaInfo`	INTEGER NOT NULL,
	`Tag`	INTEGER NOT NULL,
	PRIMARY KEY(`Id`),
	FOREIGN KEY(`Tag`) REFERENCES `Tags`(`Id`),
	FOREIGN KEY(`MediaInfo`) REFERENCES `MediaInfo`(`Id`)
);
DROP TABLE IF EXISTS `MediaInfo`;
CREATE TABLE IF NOT EXISTS `MediaInfo` (
	`Id`	INTEGER,
	`Name`	TEXT NOT NULL UNIQUE,
	`Type`	INTEGER NOT NULL,
	`Filename`	INTEGER NOT NULL UNIQUE,
	`DateTaken`	NUMERIC NOT NULL,
	`DateAdded`	NUMERIC NOT NULL,
	`Favorite`	INTEGER NOT NULL,
	`Private`	INTEGER NOT NULL,
	`Rotation`	INTEGER NOT NULL,
	PRIMARY KEY(`Id`)
);
COMMIT;
